# Generated by Django 5.2.8 on 2026-06-20 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailId',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'user_email_id',
            },
        ),
    ]
