# Generated by Django 5.2.8 on 2026-09-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useremailid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailId',
        ),
    ]
