# Generated by Django 5.2.8 on 2026-09-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_useremailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_email_send',
            field=models.BooleanField(default=False),
        ),
    ]
