USERNAME = "test_user"
USER_PASSWORD = "123test4"
DEFAULT_STATUS = "Default Status"
DEFAULT_STATUS_DESC = "Default Status Description"
CUSTOM_STATUS = "User Test Status"
CUSTOM_STATUS_DESC = "User Test Status Description"
DEFAULT_TRANSACTION_TYPE = "Default Transaction Type"
CUSTOM_TRANSACTION_TYPE = "User Test Transaction Type"
DEFAULT_CATEGORY = "Default Category"
CUSTOM_CATEGORY = "User Test Category"
CUSTOM_SUBCATEGORY = "User Test SubCategory"
NUMBER_OBJECTS_TO_GENERATE = 5
TRANSACTION_AMOUNT = 2222.99
