# Generated by Django 5.2.8 on 2026-07-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='status',
            new_name='statuses_created_e42e12_idx',
            old_name='statuses_st_created_b10c82_idx',
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
    ]
