# Generated by Django 5.2.8 on 2026-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
