# Generated by Django 5.2.8 on 2026-06-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
        ("transactions", "0003_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="statuses.status",
            ),
        ),
    ]
